### ISSUE TITLE
Does not remove branches using undefined

### ISSUE THREAD

**Issue by mrak** [zertosh/unreachable-branch-transform#12]
If there is a condition such as this:

``` javascript
if (undefined === 'development') {
  // some sensitive code only for development
}
```

It does not get removed. For reference, I am using the `envify` transform to do conditional paths based on `NODE_ENV` at build-time for client-side code

**Comment by zertosh** [comment]
Because `undefined` could've been reassigned - it's not a constant in old environments. When using `envify`, try actually defining a value for `process.env.NODE_ENV` instead of using the "prune" option.

**Comment by mrak** [comment]
Oh boy...forgot about that. 

Your workaround is the one we are currently using.

Before closing this issue, could we add a note/caveat for this case in the README?

Thanks!

**Comment by zertosh** [comment]
Sure! I'd happily accept a PR for that :smile:
