### ISSUE TITLE
returning boolean instead of expression value

### ISSUE THREAD

**Issue by jasonkarns** [zertosh/unreachable-branch-transform#9]
I'm using three transforms: coffeeify, envify, and unreachable-branch-transform; in that order.

Prior to adding unreachable-branch-transform, I had the following expression returned (after envify had run):

```
version: "0.2.0" || require('../package.json').version
```

(`"0.2.0"` was inserted statically in place of `process.env.npm_package_version`)

After adding unreachable-branch-transform, I expected:

```
version: "0.2.0"
```

But instead, received:

```
version: true
```

unreachable-branch-transform should be returning the first truthy expression value, not a raw boolean (unless, of course, the first truthy expression happens to be a literal boolean).

**Comment by zertosh** [comment]
Yeah... makes sense. I'll fix it tomorrow
